name: Build
on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-22.04 
    env:
      AUTOBUILD_PLATFORM: common
    steps:
      - run: sudo apt-get update && sudo apt-get install -y mono-complete
      - uses: secondlife/action-autobuild@v3
        with:
          archive-format: tbz2

      - uses: secondlife/action-autobuild-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
          
